name: flutter_telegram_bot
description: "Telegram API package"
version: 0.0.23
homepage: https://github.com/mammadnihal/flutter_telegram_bot
repository: https://github.com/mammadnihal/flutter_telegram_bot
issue_tracker: https://github.com/mammadnihal/flutter_telegram_bot/issues
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0